repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/pre-commit/mirrors-shfmt
    rev: v3.7.0
    hooks:
      - id: shfmt
        args: ["-i", "2", "-w"]
  - repo: https://github.com/koalaman/shellcheck
    rev: v0.9.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
        files: "\\.(md|json|ya?ml)$"
  - repo: local
    hooks:
      - id: markdownlint
        name: markdownlint-cli2
        entry: npx --yes markdownlint-cli2
        language: system
        pass_filenames: false
        files: "\\.md$"
      - id: autoformat
        name: autoformat staged files
        entry: ./scripts/autoformat.sh
        language: script
        pass_filenames: false
