name: CI
# After the repository is normalized with `git add --renormalize .` and
# `dotnet format`, this workflow enforces formatting on every pull request.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - run: |
          dotnet format --verify-no-changes || {
            echo "❌ Formatting issues detected. Run \`dotnet format\` to fix.";
            exit 1;
          }
  build:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - run: ./scripts/selfcheck.sh
      - name: Verify Code Coverage Threshold
        run: |
          COVERAGE=$(grep -Po 'line-rate="\\K[0-9.]+(?=\")' TestResults/coverage-report/coverage.xml | head -1)
          PERCENT=$(awk "BEGIN {print $COVERAGE * 100}")
          echo "Line coverage: $PERCENT%"
          awk -v p=$PERCENT 'BEGIN {exit (p<90)}'
