name: CI
# After the repository is normalized with `git add --renormalize .` and
# `dotnet format`, this workflow enforces formatting on every pull request.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ensure whitespace & analyzer rules match .editorconfig
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Restore solution
        run: dotnet restore WebDownloadr.sln
      # --- Verify EOL / indentation / trailing-whitespace
      - name: Verify whitespace & EOL
        run: |
          dotnet format whitespace --folder . --verify-no-changes || {
            echo "::error title=EOL/Whitespace Issues::Run './scripts/bootstrap-format.sh' to fix.";
            exit 1;
          }

      # --- Verify analyzer & style rules (using-order, blank lines, etc.)
      - name: Verify analyzer rules
        run: |
          dotnet format WebDownloadr.sln analyzers --verify-no-changes || {
            echo "::error title=Analyzer Formatting Issues::Run './scripts/bootstrap-format.sh' to fix.";
            exit 1;
          }
  build:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Restore solution
        run: dotnet restore WebDownloadr.sln
      - run: ./scripts/selfcheck.sh
