name: EOL Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-crlf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Detect CRLF line endings
        run: |
          bad=$(git ls-files -z | xargs -0 grep -Il $'\r' || true)
          if [ -n "$bad" ]; then
            echo "::error title=CRLF detected::Files contain CRLF line endings"
            echo "$bad"
            exit 1
          fi

